// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_BlayverthReyes.DAL;

#nullable disable

namespace P1_AP1_BlayverthReyes.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251008144239_Quinta")]
    partial class Quinta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_BlayverthReyes.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Importe")
                        .HasColumnType("REAL");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_BlayverthReyes.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_BlayverthReyes.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Rojo Pequeño",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Verde Pequeño",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Rojo Mediano",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "Verde Mediano",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 5,
                            Descripcion = "Rojo Grande",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 6,
                            Descripcion = "Verde Grande",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_BlayverthReyes.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_BlayverthReyes.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");
                });

            modelBuilder.Entity("P1_AP1_BlayverthReyes.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
